version: '3'

services:
  registry:
    image: 'rock3yu/cs328_a4_registry:v-0.1'
    ports:
      - '9000:9000'
    networks:
      - myrmi-net

  server:
    image: 'rock3yu/cs328_a4_server:v-0.1'
    depends_on:
      registry:
        condition: service_started
    networks:
      - myrmi-net

  client:
    image: 'rock3yu/cs328_a4_client:v-0.1'
    depends_on:
      server:
        condition: service_started
      registry:
        condition: service_started
    networks:
      - myrmi-net

networks:
  myrmi-net:
    driver: bridge
