# syntax=docker/dockerfile:1
FROM sgrio/java:jdk_8_alpine
MAINTAINER Kunyi Yu (12013027@mail.sustech.edu.cn)
RUN apt-get update && apt-get install -y maven
COPY pom.xml /usr/local/registry/pom.xml
COPY /src/* /usr/local/registry/src
WORKDIR /usr/local/registry
RUN mvn package
CMD ["java","-cp", "target/MyRMI_Docker_Registry-1.0-SNAPSHOT.jar", "myrmi/registry/RegistryMain"
