# syntax=docker/dockerfile:1
FROM sgrio/java:jdk_8_alpine
MAINTAINER Kunyi Yu (12013027@mail.sustech.edu.cn)
RUN apt-get update && apt-get install -y maven
COPY pom.xml /usr/local/server/pom.xml
COPY /scr/* /usr/local/server/src
WORKDIR /usr/local/server
RUN mvn package
CMD ["java","-cp", "target/MyRMI_Docker_Server-1.0-SNAPSHOT.jar", "myrmi/server/ServerMain"
